version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3 # Image officielle PostgreSQL + PostGIS
    container_name: fleet_db_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fleet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: fleet_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fleet_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: fleet_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    profiles:
      - prod

  frontend-dev:
    build:
      context: .
      dockerfile: frontend.dev.Dockerfile
    container_name: fleet_frontend_dev
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev

  adminer:
    image: adminer
    container_name: fleet_adminer
    restart: always
    ports:
      - "8082:8080"

volumes:
  postgres_data: